# Generated by Django 5.2.9 on 2026-03-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_user_pin_attempts_user_pin_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, default='Home', max_length=50),
        ),
    ]
